article/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from polls.views import *
app_name="article"

urlpatterns = [
   path('dashboard/',DashboardView.as_view(),name="dashboard"),
   path('addarticle/',AddArticleView.as_view(),name="addarticle"),
   path('article/<int:id>',DetailView.as_view(),name="detail"),
   path('videos/<int:id>',VideosView.as_view(),name="videos"),
   path('addvideos/<int:id>',AddVideosView.as_view(),name="addvideos"),
   path('update/<int:id>',UpdateArticleView.as_view(),name="update"),
   path('delete/<int:id>',DeleteArticleView.as_view(),name="delete"),
   path('comment/<int:id>',AddCommentView.as_view(),name="comment"),
   path('rate/',RateCourse.as_view(),name="rate"),
   path('complete/',CompleteVideo.as_view(),name="complete"),
   path('vote/<int:id>',FeedBackView.as_view(),name="feedback"),
   path('',ArticlesView.as_view(),name="articles"),
   path('takencourses/',TakenCoursesView.as_view(),name="takencourses"),
   path('takecourse/<int:id>',TakeCourse.as_view(),name="take"),
   path('dropcourse/<int:id>',DropCourse.as_view(),name="drop"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name="index"),
    path('about/', views.AboutView.as_view(),name="about"),
    path('detail/<int:id>', views.DetailView.as_view(),name="detail"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name="user"

urlpatterns = [
   path('signup/',SignUpView.as_view(),name="signup"),
   path('signup/student/',StudentSignUpView.as_view(),name="student_signup"),
   path('signup/teacher',TeacherSignUpView.as_view(),name="teacher_signup"),
   path('login/',Login2View.as_view(),name="login"),
   path('logout/',Logout2View.as_view(),name="logout"),
   path('loginins/',LoginInsView.as_view(),name="loginins"),
   path('loginstu/',LoginStuView.as_view(),name="loginstu"),
]
"""path('register/',RegisterView.as_view(),name="register"),
path('login/',LoginUserView.as_view(),name="login"),
path('logout/',LogoutUserView.as_view(),name="logout"),"""

article/models.py
from importlib.resources import contents
from django.db import models
from ckeditor.fields import RichTextField
from django.core.validators import MaxValueValidator, MinValueValidator
from embed_video.fields import EmbedVideoField
#from user.models import User
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("user.User",on_delete=models.CASCADE,verbose_name="Author")
    title = models.CharField(max_length=50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank=True,null=True,verbose_name="Add image to the article")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']


class Video(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Article", related_name="videos")
    title = models.CharField(max_length=100)
    video_id = models.CharField(max_length=25)
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()
    duration = models.FloatField(default=0)
    duration_str = models.CharField(max_length=25)


    def __str__(self):
        return str(self.title)

    class Meta:
        ordering= ['added']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Article",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="Name")
    comment_content = models.CharField(max_length=200,verbose_name="comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self',null=True,blank=True,on_delete=models.CASCADE,related_name='replies')



    def __str__(self) -> str:
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

class TakenCourse(models.Model):
    student = models.ForeignKey("user.Student", on_delete=models.CASCADE, related_name='taken_courses')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='taken_courses')
    is_takencourse_completed = models.FloatField(default=0)
    added = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(null=True,
                                validators=[
                                    MaxValueValidator(5),
                                    MinValueValidator(0),
                                ]
    )   #rating for the taken course
    class Meta:
        ordering = ['added']
    def __str__(self):
        return self.article.title

class TakenCourseVideo(models.Model):
    takencourse = models.ForeignKey(TakenCourse,on_delete=models.CASCADE)
    video = models.ForeignKey(Video,on_delete=models.CASCADE)
    is_completed_video = models.BooleanField(default=False)

    def __str__(self):
        return self.video.title

article/forms.py
from django import forms
from .models import Article,Video

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields= ["title","content","article_image"]

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ["title","url","video_id"]

"""class TakenCourseForm(forms.ModelForm):
    class Meta:
        model = TakenCourse
        fields = ["title","content","article_image"]

"""

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.db.models import Avg,F,Sum
from django.core.paginator import Paginator

import article
from .forms import ArticleForm,VideoForm
from django.contrib import messages
from .models import Article,Comment,TakenCourse,Video,TakenCourseVideo

from user.decorators import teacher_required,student_required
from user.models import Student,User

import json
import urllib.request
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
API_KEY ="AIzaSyDuTuqB9Xv5aocjJy4KfxkXUV3vIkU6AGs"



class ArticlesView(View):
    def get(self,request,*args,**kwargs):
        keyword = request.GET.get("keyword")


        articles = Article.objects.annotate(avg_score=Avg('taken_courses__score'),duration_sum=Sum('videos__duration'))



        if request.user.is_student:
            student = get_object_or_404(Student, user_id=request.user.id)

            # a loop to check the courses that are not taken by this student and these courses will be added to articles list
            for course in Article.objects.all():
                if course in student.courses.all():
                    articles = articles.exclude(title__contains=course.title)
                else:
                    pass


            if keyword:
                articles = articles.filter(title__icontains=keyword)
                paginator = Paginator(articles, 3)
                page_number = request.GET.get('page')
                page_obj = paginator.get_page(page_number)
                return render(request, "articles.html", {"page_obj": page_obj})

            paginator = Paginator(articles, 3)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            return render(request, "articles.html", {"page_obj": page_obj})


        if keyword:
            articles = articles.filter(title__icontains=keyword)
            paginator = Paginator(articles, 3)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            return render(request, "articles.html", {"page_obj": page_obj})

        paginator = Paginator(articles, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


        return render(request, "articles.html", {"page_obj": page_obj})





#----------------------------------------------

class TakenCoursesView(View):
    def get(self, request, *args, **kwargs):
        keyword = request.GET.get("keyword")
        student = get_object_or_404(Student, user_id=request.user.id)
        courses = TakenCourse.objects.filter(student_id=student.user_id).annotate(avg_score=Avg('score')).order_by('added')


        for course in courses:
            takencourse_videos = TakenCourseVideo.objects.filter(takencourse_id=course.id)
            completed = 0 #number of completed videos
            for video in takencourse_videos:
                if video.is_completed_video:
                    completed = completed+1

            if completed:
                course.is_takencourse_completed = (completed/len(takencourse_videos))*100



        if keyword:
            courses = courses.filter(article__title__icontains=keyword)

            paginator = Paginator(courses, 3)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            return render(request, "taken-courses.html", {"page_obj": page_obj})

        paginator = Paginator(courses, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, "taken-courses.html", {"page_obj": page_obj})






#----------------------------------------------
class IndexView(View):
    def get(self,request):

        articles = Article.objects.annotate(avg_score=Avg('taken_courses__score')).order_by(F('avg_score').desc(nulls_last=True))

        paginator = Paginator(articles, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)



        return render(request,"index.html",{"page_obj":page_obj})

#---------------------------------------------

class AboutView(View):
    def get(self,request):
        return render(request, "about.html")



#-----------------------------------------------------------
class DashboardView(View):
    @method_decorator(login_required(login_url="user:login"))
    def get(self,request):
        articles = Article.objects.filter(author=request.user)

        paginator = Paginator(articles, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, "dashboard.html", {'page_obj':page_obj})



#----------------------------------------------------------
class DetailView(View):
    @method_decorator(login_required(login_url="user:login"))
    def get(self,request,id):
        article = get_object_or_404(Article, id=id)
        comments = article.comments.all()
        flag=False
        if request.user.is_student:
            student = get_object_or_404(Student, user_id=request.user.id)
            if article in student.courses.all():
                flag=True


        return render(request, "detail.html", {"article": article, "comments": comments,"flag":flag})

#-------------------------------------------------

class VideosView(View):
    @method_decorator(login_required(login_url="user:login"))
    def get(self,request,id):
        article = get_object_or_404(Article, id=id)
        videos = article.videos.all()
        flag = False
        if request.user.is_student:
            student = get_object_or_404(Student, user_id=request.user.id)
            if article in student.courses.all():
                flag = True
                takencourse = get_object_or_404(TakenCourse, article_id=id, student_id=request.user.id)
                takenvideos =TakenCourseVideo.objects.filter(takencourse_id=takencourse.id)

                return render(request,"takenvideos.html",{"takenvideos":takenvideos,"flag":flag})




        return render(request, "videos.html", {"videos": videos,"flag":flag})


#-------------------------------------------------
class AddVideosView(View):
    @method_decorator(login_required(login_url="user:login"))

    def get(self, request,id):
        form = VideoForm(None)

        return render(request, "videopage.html", {"form": form})


    @method_decorator(login_required(login_url="user:login"))

    def post(self, request,id):
        form = VideoForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            video = form.save(commit=False)
            article = get_object_or_404(Article, id=id)
            video.title = request.POST.get('title')
            video.url = request.POST.get('url')
            video_id = request.POST.get('video_id')
            video.video_id = video_id


            #calculation of the video duration
            total_second= duration_calc(video_id)


            video.duration = total_second
            min = total_second // 60
            sec = total_second % 60
            video.duration_str = str(min)+'m ' + str(sec) + 's '
            video.article = article
            video.save()

            messages.success(request, "Course has been successfully created")
            return redirect("article:dashboard")

        return render(request, "videopage.html", {"form": form})

#----------------------------------------------

# a function to calculate duration of the video
def duration_calc(video_id):
    video_id = video_id
    api_key = API_KEY
    searchUrl = "https://www.googleapis.com/youtube/v3/videos?id=" + video_id + "&key=" + api_key + "&part=contentDetails"
    response = urllib.request.urlopen(searchUrl).read()
    data = json.loads(response)
    all_data = data['items']
    contentDetails = all_data[0]['contentDetails']
    duration = contentDetails['duration']
    new_dur = duration.split('PT')[1].split('M')
    min = float(new_dur[0])
    sec = new_dur[1].split('S')[0]
    if(sec != ''):
        sec = float(sec)
    else:
        sec = 0

    return min*60 + sec



#-------------------------------------------------


class AddArticleView(LoginRequiredMixin,View):

    #@method_decorator(login_required(login_url="user:login"))
    @method_decorator(teacher_required(login_url="user:loginins"))
    def get(self,request):
        form = ArticleForm(None)

        return render(request, "addarticle.html", {"form": form})


    #@method_decorator(login_required(login_url="user:login"))
    @method_decorator(teacher_required(login_url="user:loginins"))
    def post(self, request):
        form = ArticleForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            article = form.save(commit=False)

            article.author = request.user
            article.save()

            messages.success(request, "Course has been successfully created")
            return redirect("article:dashboard")

        return render(request, "addarticle.html", {"form": form})


#--------------------------------

## add teacher required methods to necessary articleviews
class UpdateArticleView(View):
    @method_decorator(login_required(login_url="user:login"))
    @method_decorator(teacher_required(login_url="user:loginins"))
    def get(self,request,id):
        article = get_object_or_404(Article, id=id)

        form = ArticleForm(None, instance=article)
        return render(request, "update.html", {"form": form})

    @method_decorator(login_required(login_url="user:login"))
    @method_decorator(teacher_required(login_url="user:loginins"))
    def post(self, request, id):
        article = get_object_or_404(Article, id=id)

templates/addarticle.html
{%extends "layout.html"%}
{% load crispy_forms_filters %}

{% block body%}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Post</button>
        </form>
    </div>
  </div>

{%endblock body%}

templates/articles.html
{%extends "layout.html" %}
{% load mathfilters %}
{%block body%}

<div class="row">
    <div class="col-lg-20">
        <div class="col-lg-20">
            <h1>Available Courses</h1>
            <hr>
        </div>
    </div>
</div>

<div class ="row">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
      </div>
</div>


{%for article in page_obj%}

<div class="row">
    <div class="col-lg-10">
        <!-- Post content-->
        <article>
            
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="/articles/article/{{article.id}}"><h1 class="fw-bolder mb-1">{{article.title}}</h1> </a>
                <hr>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
                <!-- Post categories-->
                <hr>
            </header>
            <!-- Preview image figure-->
            {%if article.article_image %}
            <a href="/articles/article/{{article.id}}">
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></figure>
            </a>
            {%endif%}
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content|safe|truncatewords:25}}
                </p>
                <a style="float:right" href="/articles/article/{{article.id}}" class="btn btn-danger"> Read more</a>
                <br>
            </section>
            <p>
               <span class="badge badge-info" >Course Rating:</span>
                {% if article.avg_score %}
                     <span class="badge badge-pill badge-success">{{article.avg_score}}</span>
                {% else %}
                    Course hasn't been rated by anyone yet...
                {% endif %}

                </p>
                <p>
                   <span class="badge badge-info" >Course Length:</span>
                    {% if article.duration_sum %}
                         <span class="badge badge-pill badge-success">{{article.duration_sum |intdiv:60}} min {{article.duration_sum |mod:60}} sec </span>
                    {% else %}
                        ...
                    {% endif %}

                </p>
        </article>
        
    </div>
    
</div>

{%endfor%}


<br>
<div class="pagination">
    <span class="step-links">
    <span class="badge badge-warning" >
           {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>

        {% endif %}
    </span>
    <span class="badge badge-info" >
           {% if page_obj.has_previous %}

            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    </span>

        <span class="current">
            <span class="badge badge-success" >
                <strong>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. </strong>
            </span>

        </span>
        <span class="badge badge-info" >
           {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>

        {% endif %}

        </span>
        <span class="badge badge-warning" >
           {% if page_obj.has_next %}

            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

        </span>


    </span>
</div>


{%endblock body%}

templates/feedback.html
{% extends "layout.html" %}
{% load crispy_forms_filters %}

{% block body  %}
{% load crispy_forms_tags %}

    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <legend class="text-center mt-4">Evaluation Form</legend>
            <p class="text-muted">* compulsory</p>
            {{ form | crispy }}
            <div class="form-group">
                <button class="btn btn-success" type="submit">Submit Evaluation</button>
            </div>
        </form>
        <div>
            <button> <a href="{% url 'index' %}">Cancel</a> </button>
        </div>
    </div>



{% endblock body  %}

templates/home.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center" >
    <h3>Welcome to my blog</h3>
    <p>
        This blog will display your articles!
    </p>
</div>

    {% if request.user.is_authenticated %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Well done!</h4>
           Logged in as {{request.user.username}}
        </div>
    {%else%}
    <div class="alert alert-warning" role="alert">
            Not logged in
    </div>
    {%endif%}




{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center" >
    <h3>Welcome to Moursera</h3>
    <p>
        This an course application. You can develop yourself in any field. Begin to learn!!!
    </p>
</div>
 <br><br><br><br>
    <h2><strong>Top Rated Courses</strong></h2>
    <hr>
    &nbsp;&nbsp;


{%for article in page_obj%}

<div class="row">
    <div class="col-lg-10">
        <!-- Post content-->
        <article>

            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="/articles/article/{{article.id}}"><h1 class="fw-bolder mb-1">{{article.title}}</h1> </a>
                <hr>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
                <!-- Post categories-->
                <hr>
            </header>
            <!-- Preview image figure-->
            {%if article.article_image %}
            <a href="/articles/article/{{article.id}}">
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></figure>
            </a>
            {%endif%}
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content|safe|truncatewords:25}}
                </p>
                <a style="float:right" href="/articles/article/{{article.id}}" class="btn btn-danger"> Read more</a>
                <br>
            </section>
            <p>
               <span class="badge badge-info" >Course Rating:</span>
                {% if article.avg_score %}
                   <span class="badge badge-pill badge-success">{{article.avg_score}}</span>
                {% else %}
                    Course hasn't been rated by anyone yet...
                {% endif %}

                </p>
        </article>

    </div>

</div>

{%endfor%}
<br>
<div class="pagination">
    <span class="step-links">
    <span class="badge badge-warning" >
           {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>

        {% endif %}
    </span>
    <span class="badge badge-info" >
           {% if page_obj.has_previous %}

            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
    </span>

        <span class="current">
            <span class="badge badge-success" >
                <strong>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. </strong>
            </span>

        </span>
        <span class="badge badge-info" >
           {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>

        {% endif %}

        </span>
        <span class="badge badge-warning" >
           {% if page_obj.has_next %}

            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}

        </span>


    </span>
</div>

<br>
<hr>
    {% if request.user.is_authenticated %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Well done!</h4>
           Logged in as {{request.user.username}}
        </div>
    {%else%}
    <div class="alert alert-warning" role="alert">
            Not logged in
    </div>
    {%endif%}




{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static%} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <title>Document</title>
</head>
<body>
    {%include "includes/navbar.html" %}
    <div style="margin-top:100px; margin-bottom:50px " class="container">
        {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}

        {% block body %}
        {% endblock body %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main2.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>



</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/loginstu.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="alert alert-danger" role="alert">
  You have to be an Student for this action!
    Login as Student!!!
</div>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>
            <br>
        </form>
    </div>

<br><br>
  </div>
    <div class="alert alert-info" role="alert">
    If you don't have an Student account SignUp from here:
</div>
    <button type="button" class="btn btn-outline-primary">
        <a href="{% url 'user:student_signup' %}" class="btn btn-teacher btn-lg" role="button">I'd like to be an Student</a>
    </button>

{% endblock body %}

templates/register.html
{%extends "layout.html" %}

{%block body%}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Register</button>
        </form>
    </div>
  </div>

{%endblock body%}

templates/signup.html
{% extends 'layout.html' %}

{% block body %}
  <h2>Sign up for a free account</h2>
  <p class="lead">Select below the type of account you want to create</p>
  <a href="{% url 'user:student_signup' %}" class="btn btn-student btn-lg" role="button">I'm a student</a>
  <a href="{% url 'user:teacher_signup' %}" class="btn btn-teacher btn-lg" role="button">I'm a Instructor</a>
{% endblock %}

templates/signup_form.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/takenvideos.html
{% extends "layout.html" %}
{% load embed_video_tags %}


{% block body %}
    {% if flag %}
    <h1 class="mb-5">Course Videos</h1>
    <div class="d-flex flex-wrap">
        {% for takenvideo in takenvideos %}
        <div class="px-3 mb-5">
            <div class="d-flex justify justify-content-start">

                <h5 > <strong>{{ forloop.counter }}. Lesson:  <h5> {{ takenvideo.video.title }} </h5> </strong> </h5>

            </div>
            {% video takenvideo.video.url '426x240' %}

            <h6> Course duration: <span class="badge badge-pill badge-success">{{ takenvideo.video.duration_str }}</span> <span class="badge badge-pill badge-success">{{ takenvideo.video.duration }}<span> seconds </h6>


            {% if takenvideo.is_completed_video %}
                <button onclick="completeVideo({{ takenvideo.video.id }})" type="button" class="btn btn-warning" id="complete"><label for="complete">Uncomplete video </label>

                <div><span class="badge badge-pill badge-warning" id="confirm-box"></span></div>


            {% else %}
                <button onclick="completeVideo({{ takenvideo.video.id }})" type="button" class="btn btn-success" id="complete"><label for="complete">Complete video </label>

               <div><span class="badge badge-pill badge-success" id="confirm-box"></span></div>
            {% endif %}

        </div>


    </div>

    {% endfor %}
    {% else %}
        <h2> <strong> If you want to watch videos you have to own course ;)) !</strong> </h2>
    {% endif %}

<script>



const completeVideo = (id) =>{
    $.ajax({
                type: 'POST',
                url: "{% url 'article:complete' %}",
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'video_id': id,

                },
                success: function(response){
                    //console.log(response)
                    confirmBox.innerHTML = `<h6>Action is succesful!</h6>`
                },
                error: function(error){
                    //console.log(error)
                    //confirmBox.innerHTML = '<h6>Ups... something went wrong</h6>'
                }
            })}

</script>


{% endblock %}

templates/update.html
{%extends "layout.html"%}

{% block body%}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update</button>
        </form>
    </div>
  </div>

{%endblock body%}